### ISSUE TITLE
Installation bug with alignak-2.0 and ubuntu 16.04

### ISSUE THREAD

**Issue by jbiousse** [Alignak-monitoring/alignak#1049]
With an alignak 2.0 on a ubuntu 16.04, you can't correctly launch the application.

I have install the application with **sudo apt install python3-alignak** and the services are all registered in lib/systemd/system/alignak.

- But when i do **systemctl  status alignak**
> alignak is active (exited)

- So i have decide to watch the services **systemctl  status alignak-arbiter@master.service ● alignak-arbiter@master.service**
 and i got  
> Failed to start Alignak arbiter master daemon instance.

Then i check the syslog and i found this  : 
https://zupimages.net/up/18/37/rbdo.png

**Comment by mohierf** [comment]
The problem is because of a bad location of the installed source code ... as of now, the source code is installed in a directory that is not located in the PYTHONPATH :/

1. On debian, the system installed packages should be in *dist-packages* directory and not *site-packages* 
2. Alignak source code is installed in */usr/local/lib/python3.6* whereas Python 3.6 is not the one installed on Ubuntu 16 which has python 3.5 ...

**Comment by mohierf** [comment]
I will add more information about this requirement in the Alignak installation doc!

**Comment by mohierf** [comment]
I updated the Alignak installation doc: http://docs.alignak.net/en/latest/02_installation/00_requirements.html#python-version
