### ISSUE TITLE
Separate data to class/functions

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#114]
I think we need to separate data to class/function.

For exemple, we have 
```
 'contacts': <shinken.objects.contact.Contacts object at 0x808eaa6d0
```
instead
```
'contacts' : {'contact_name': 'koinkoin', 'alias': 'koin2'}
```

The main reasons: 
* read code is more easier
* have some easier to test functions

Because when call a function we add the data dict in parameter and return a data or the complete dict transformed (depend of cases).

The issue #30 is related to this

For the pylint, we see that we have many problem with variables not initialized, invalid, and others things. There are very lots of problems and I think code this issue before fix pylint can same us lot of time after because the code will be more easier to read and will have less errors in pylint

**Comment by gst** [comment]
> For exemple, we have
>  'contacts': <shinken.objects.contact.Contacts object at 0x808eaa6d0
> instead
> 'contacts' : {'contact_name': 'koinkoin', 'alias': 'koin2'}

heuh..  add/implement a `def __str__` and/or `__repr__` to the Contact class (and others "items" classes if need to be ; I recall I had begun to do that sometimes ago, don't remember how far / merged this had been on the other side).

because `'contacts': <shinken.objects.contact.Contacts object at 0x808eaa6d0` is clearly something you got in a log output or in debug session.. and if that's what bother you then yeah the *only* good thing to do here is to add **\_\_str\_\_ and/or \_\_repr\_\_** where appropriate, nothing else ;)

**Comment by ddurieux** [comment]
oky

**Comment by gst** [comment]
ping

**Comment by ddurieux** [comment]
See #294
