### ISSUE TITLE
Packaging process 

### ISSUE THREAD

**Issue by Seb-Solon** [Alignak-monitoring/alignak#174]
Hi,

I'm trying to centralize talk we had about how packaging of Alignak will be implemented.

As far as I remember we stayed on 1 branch for packaging type. Like rpm / debian. So that we don't have packaging file in master/develop.

I can't remember the pros cons of that. 

Linked to #91 (remove for fedora maybe)

**Comment by ddurieux** [comment]
We don't have decided to add packaging files (deb, rpm, bsd...) in an other repository?

**Comment by Seb-Solon** [comment]
Branch / repo is basically the same (not with the code)

**Comment by titilambert** [comment]
in this case, branch means detached branch ... a new repo could be easier ?
In this repo/branch, there will be: files and folder used for packaging (spec files, debian, ...)
And a tarball of Alignak master.
What do you think ?

**Comment by Seb-Solon** [comment]
Yeah a repo packaging with branch debian / rpm could be great no?

**Comment by ddurieux** [comment]
A branch or a folder for each packaging system (prefer folder because it's more easier to read)

**Comment by gst** [comment]
Sorry but don't remember too the talks we had about this..

and sorry twice but I dislike the idea to create yet another repository for this, why not have a folder named 'packaging' in our top and in it have subfolders : debian, fedora, redhat, ~~ubuntu~~ (no this is mean for real distribution) and so on .. 

were there some cons about this possibility ?

**Comment by hvad** [comment]
Hi,

I begin work to make rpm for fedora/epel and i think we just need source for that work correctly ;-). 

You can make debian directory on that repository and create a spec file for fedora/epel. 

But the main jobs is to work with systemd ^^. 

See you soon on irc

**Comment by gst** [comment]
related: https://github.com/Alignak-monitoring/alignak/issues/174

**Comment by titilambert** [comment]
The packaging is already done on surveil project... see here: https://github.com/surveil/surveil-packaging/blob/centos/alignak/alignak.spec

**Comment by Seb-Solon** [comment]
First spec draft done on alignak-packaging.

Links to help : https://fedoraproject.org/wiki/How_to_create_an_RPM_package, https://fedoraproject.org/wiki/Packaging:RPMMacros

Macro list are very useful when you look for a specific file.

**Comment by hvad** [comment]
Hi,

i known because i use everyday ^^. See ->
http://paste.fedoraproject.org/269102/17308144

Bye

2015-09-18 22:37 GMT+02:00 Sébastien Coavoux <notifications@github.com>:

> First spec draft done on alignak-packaging.
>
> Links to help :
> https://fedoraproject.org/wiki/How_to_create_an_RPM_package,
> https://fedoraproject.org/wiki/Packaging:RPMMacros
>
> Macro list are very useful when you look for a specific file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Alignak-monitoring/alignak/issues/174#issuecomment-141562051>
> .
>



-- 
David Hannequin

**Comment by hvad** [comment]
See https://fedoraproject.org/wiki/Packaging:Python

**Comment by Seb-Solon** [comment]
Ok first working file is done. We have to agree on some points : 

* Package structure  : I'm for one alignak-common and one alignak-doc packages. We could split by daemon but it's not really worth it and I'm afraid of conflicts. Two package will provide the same files (python files)

* Install path for python binaries : In the draft it's /usr/bin, we could argue on /usr/sbin

* Requirements : I'm not sure for python-imporlib. Maybe we will need some if to add it to requirement. I'm afraid recent (f22) distro will fail because the package is not installed but it's now in standard python lib

* Init script / systemd : Another if to do? The draft copy /etc/init.d/alignak* shell scripts and /etc/default/alignak files

* .pth file : I'm not 100% sure this is needed, I removed it in packaging

See @806f976ba4036087226549f059666e1a8ee7823f . I'm not sure if I will PR on "rpm" or "fXX" branch because I'm afraid we will need several spec.

**Comment by aviau** [comment]
> Init script / systemd : Another if to do?

I don't know for Fedora, but in Debian we ship both the sysvinit and systemd files. So that shouldn't be an ``if``.

> we could argue on /usr/sbin

Absolutely


>  I'm for one alignak-common and one alignak-doc packages

I agree.

**Comment by hvad** [comment]
Hi, my point of view :

Package structure : I'm for one alignak-common and one alignak-doc packages. We could split by daemon but it's not really worth it and I'm afraid of conflicts. Two package will provide the same files (python files)

Yes, alignak-common is good idea but i not sure for doc.

Install path for python binaries : In the draft it's /usr/bin, we could argue on /usr/sbin

It's more an habit than a rule.

Requirements : I'm not sure for python-imporlib. Maybe we will need some if to add it to requirement. I'm afraid recent (f22) distro will fail because the package is not installed but it's now in standard python lib

I think it's on standard python lib until centos 7 and fedora 20.

Init script / systemd : Another if to do? The draft copy /etc/init.d/alignak* shell scripts and /etc/default/alignak files

I prefer systemd script rule and i think we must forget sysV for Linux.

.pth file : I'm not 100% sure this is needed, I removed it in packaging

Yes

**Comment by Seb-Solon** [comment]
I forgot one last thing : 
The setup generate .pyc and .pyo. Fedora pacaking suggest to keep them but maybe both file for each python file is a bit overkill. I don't think wee need a .pyc and a .pyo file for a specific file. I need to look documentation/usage. If you have opinion/idea about this feel free to help me.

**Comment by gst** [comment]
> The setup generate .pyc and .pyo. Fedora pacaking suggest to keep them but maybe both file for each python file is a bit overkill. I don't think wee need a .pyc and a .pyo file for a specific file.

*pyc are the (pre-)compiled source files.
and *pyo are same than *pyc but for "optimized" python calls (`python -O some_script.py`, which actually only remove/delete the `assert` from the sources).

I think it's better/simpler to keep both ; that doesn't hurt at all (some kbytes used, that's all)..

why would you bother remove them, they would be anyway rebuild/regenerated where the package would be executed the first time..  normally, because if, for instance, the file system where the source is located/installed is readonly then this wouldn't be possible. I think that's exactly the goal of the pre-compile during package build : have the *pyc & *pyo (directly) available (even if readonly filesystem so) on the installed destination..

**Comment by Seb-Solon** [comment]
Debian packaging is working. Waiting for review of @titilambert

**Comment by mohierf** [comment]
What about this @Seb-Solon @titilambert @ddurieux @hvad

**Comment by mohierf** [comment]
@Seb-Solon ? What about this now ?

**Comment by Seb-Solon** [comment]
See  Alignak-monitoring/alignak-packaging for all packaging related stuff
