### ISSUE TITLE
Clean objects 'properties' and replace with real Python attributes

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#442]
Currently almost all the objects declare a `properties` dictionary attribute that contains mainly the properties extracted from the flat-files configuration.

Pros:
- associate parsing tools to each property

Cons:
- the code is not the best Pythonic ever and we cannot take the best of modern IDE like Pycharm ...
- many accessor functions are defined

**Comment by Seb-Solon** [comment]
I think you will lose some genericity in object and dynamic optimization such as __slots__ if you do so

**Comment by mohierf** [comment]
Can you tell more about **slots**? What are they and what for?

**Comment by Seb-Solon** [comment]
__slots___ are for memory usage optimization. Basically when this attribute exists python fixes the content of __dict__ attribute to reduce memoirize size when storing data. The current implementation is not really good because we are only using part of this feature. 

See http://stackoverflow.com/questions/472000/usage-of-slots. 

Maybe we should try to remove it and see.

**Comment by mohierf** [comment]
Yes, we should build a dedicated test to measure memory consumption with and without __slots__

**Comment by mohierf** [comment]
+1 for this to have a cleaner pylint configuration !

**Comment by mohierf** [comment]
To do list for objects refactoring:
 - [ ] dedicated logger level for debug and test purpose
 - [ ] replace '0' '1' with boolean values
 - [ ] remove unuseful methods (eg. getter/setter for simple properties)

**Comment by mohierf** [comment]
Pros and Cons ... but the object genericity and some methods are really easier with the current implementation
