### ISSUE TITLE
Add PyOpenSSL in the project requirements

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#549]
Let's assume the following:
- it is recommended to use SSL for inter-daemon communication in a distributed environment
- as stated in the requirements, we need a specific PyOpenSSL version (0.14)
- we are obliged to install and uninstall PyOpenSSL to make full tests of the application
- it is not an important constraint to have PyOpenSSL installed even if it not used

I propose to add `pyopenssl==0.14`to the requirements.txt file

@ddurieux @Seb-Solon : what about his ?

**Comment by Seb-Solon** [comment]
2  > as stated in the requirements, we can't put the dep here because pyopenssl == 0.14 is not packaged yet. So we won't be able to install alignak if there is a dep on pyopenssl.

3 > you should put this requirement in the test requirements. Instead of doing it manually. we can edit travis file as we already have a matrix to have multiple test requirements.

4> It is, as packaging (debian) use this to make the dep on the alignak package.

**Comment by ddurieux** [comment]
For point 3. you're right, we can use travis matrix.

For point 2, I think we must not wait packaging to add something we think it's required. If all software do this, many lib never packaged :D . In conlusion, the packager must do the job and we (the developer) may not restrict use lib / simplify code because of packaging

**Comment by mohierf** [comment]
And so, what is the conclusion of this? From what I understand, we do not change anything ... so I close this issue

**Comment by Seb-Solon** [comment]
@ddurieux  If you add this requirement the packaging of alignak will be useless. The package can't have pyopenssl==0.14 (unless we manully package this lib but I don't want to) otherwise it won't be installable. So if you enforce this I will have to revert that before packaging.

**Comment by Seb-Solon** [comment]
Linked with Alignak-monitoring/alignak-packaging#11
