### ISSUE TITLE
[proposal] drop python2.6 support

### ISSUE THREAD

**Issue by gst** [Alignak-monitoring/alignak#56]
1) it's so old
2) afaik : it's not anymore used as default system python for most of linux distributions, 
    even debian stable !!
3) there are _at least some_ code paths dedicated to it in alignak.. which is not good. 
and when you look more closely at these specific code paths (which unfortunately are not always easily spottable, thx to history..) :  you think "what!?"

**Comment by ddurieux** [comment]
I'm ok with that +1

**Comment by gst** [comment]
for the very rare times where a distribution has still python2.6 as **system** python,
well : there are almost always (there should be) packages available for python2.7  (example: centos6 : http://rpm.pbone.net/index.php3?stat=3&search=python27-python&srodzaj=3&dist[]=79)

**Comment by Seb-Solon** [comment]
Redhat 6 will be there until November 2020 and redhat5 with extended support :  https://access.redhat.com/support/policy/updates/errata 

The fact that there is no official 2.7 package may be a big NOPE for prod env. We could build and host a python2.7 RPM on our future repos but still, it's not an official one.

I think we have to see which specific part a python2.6 to see if it's worth it or not.

**Comment by gst** [comment]
I agree that there are not lot of diff between 2.6 and 2.7 and as such it's (should be rather) easy for us to keep it support.
So, well, I guess we will continue to support it, maybe still for few years (<= 5 I would hope).

**Comment by mohierf** [comment]
A sum-up of main differences would be appreciated ... I did not care at all about Python 2.6 in the Web UI !

**Comment by algorys** [comment]
I think now python 2.6 is rarely present on recent distributions. 

Assuming that Alignak will not be stable before some time , Python 2.7 and Python 3.x seem enough.

**Comment by Seb-Solon** [comment]
Redhat 6 is still here until 2020. But maybe we will decide to drop support for rh6 / centos6 one day.

Ubuntu has 2.7 by default since 12.04 (precise). So the Ubuntu support is not dropped if we drop 2.6 : https://wiki.ubuntu.com/LTS

My concern is also based on : https://github.com/Alignak-monitoring/alignak-docker . All those OS are using 2.7 already so it's seems fine too.

Going back to Dedhat, May 10, 2017 can be a date to drop 2.6 support and other "old"  distro.
May 10, 2017 is the date of End of Production 2 for RH6 and RH5 will be in End of Extended Life-cycle Support. It is also past the date of End of life for Ubuntu 12.04

So maybe we can handle this 1 extra year?

**Comment by ddurieux** [comment]
Python 2.6 no supported by dev since 2013, so drop it

**Comment by mohierf** [comment]
Dropped with the newcoming 1.1 version
