### ISSUE TITLE
Trigger notifications inside Alignak-app 

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring/alignak#631]
Actually, Alignak-app (App) trigger notification on desktop by simply check states of hosts and services.

One feature that could be pretty good would be that alignak store somewhere in backend a notification and App check regularly in backend what is already send or not to the user...

Here is a small example of what this could give:

1. Alignak send a notification.
2. This is stored in backend
3. App checks every "x" seconds in the backend (with client) the notifications that have be send.
3. App retrieves notifications that have not yet been displayed / acknowledged by the user and display it.

The advantage of such a system is that  provides one more way to warn the user.

Even if you no longer have a mail server but still access to Alignak, the user can continue to receive notifications.

**Comment by mohierf** [comment]
I re-created this issue here: https://github.com/Alignak-monitoring-contrib/alignak-app/issues/58 because it is much more appropriate IMHO :wink:.

-----

It is not necessary to make a specific development/modification in Alignak for this. You simply need to configure a notification script that will send the notification to the appropriate destination. And even this does not look necessary ... the information about the sent notification are still available in the Alignak "Monitoring logs".

I added a comment in the new issue with my design ideas about this feature ... follow the link for more about it: https://github.com/Alignak-monitoring-contrib/alignak-app/issues/58

**Comment by mohierf** [comment]
Closing ...
